### ISSUE TITLE
Default register

### ISSUE THREAD

**Issue by crazyTauron** [TheShark34/OpenAuth-Server#1]
Hi, First of all you made really good work and i want thanks for its. I'm learning many things. 
I have a little problem. I'm trying to use default register but when i click on submit button i have a HTTP 500 error on IE11 and blank page(error on first query) on Chrome, how can i solve? I didn't modify your code

**Comment by Vahelnir** [comment]
What is your host ?
Do you have any errors ? Pastebin them here.

**Comment by crazyTauron** [comment]
Hi, i have a server on kimsufi. I use apache2 with mysql and i set 777 permission to server folder.

**Comment by Vahelnir** [comment]
Hum, i developped the application on a Debian VM with apache2 and it's work nice.
Do you have any errors ?

**Comment by crazyTauron** [comment]
Console says that there is an error on the code but doesn't say where and what. Now i'm installing xampp to try on my pc

**Comment by Vahelnir** [comment]
Do you have some news ?

**Comment by crazyTauron** [comment]
Yep. the problem was Core/Queries, Core/Database that can't be include on register.php. I solved adding: include "Core/Queries.php"; include "core/functions.php"; on register.php and include "core/Database.php"; include "core/Config.php"; on Queries.php. Now register work. 

I'm probably wrong because now authenticate doesn't work :(

The first error was "Fatal error: Class 'Core\Queries' not found in C:\xampp\htdocs\OpenAuth-Server\server\app\register.php on line 32" I had solve with include but this solution broke other page

**Comment by Vahelnir** [comment]
What url do you use to access to the register page ?

**Comment by crazyTauron** [comment]
http://localhost/OpenAuth-Server/server/app/register.php

i tried to change Core\Queries in core\queries linke folder but nothing

**Comment by Vahelnir** [comment]
To install OpenAuth server, you have to extract the "installer.php" into a directory, go to http://yoururl/installer.php or http://yoururl/yourdir/installer.php.
Next you are redirected on the install page where you have to enter your informations like mysql informations and then the url are http://yoururl/register for exemple.

**Comment by crazyTauron** [comment]
yes i did it. I check on mysql and table exist but i have the same problem on line 31
$req = Core\Queries......

**Comment by Vahelnir** [comment]
Are you trying to access to /app/register.php or /register ?

**Comment by crazyTauron** [comment]
Oh god now work! /register.php doesn't work but /register yes! Why? If i don't steal too much time

**Comment by Vahelnir** [comment]
It's because i make a rewrite url system to have better URLs and the dispatcher (index.php) imports the right files in function of the URLs

**Comment by crazyTauron** [comment]
Thanks you very much :)

**Comment by Vahelnir** [comment]
No problem ! :)
