### ISSUE TITLE
Questions sur l'authentification

### ISSUE THREAD

**Issue by DarkScientist** [TheShark34/OpenAuth-Server#11]
Bonjour,
J'ai une question dont je dois vous faire part. 

J'ai un site Web MineWeb, un launcher SKCraft et le serveur Yggdrasil. 

J'aimerai savoir si je peux réaliser ces actions :
Est il possible d'avoir l'authentification Yggdrasil liée à MineWeb (ça je sais faire je pense) mais tout en gardant la notion de comptes premiums (en gros, relier les utilisateurs à Mojang pour qu'ils soient premium mais validés via MineWeb.
Je ne souhaite pas l'intégrer sur mon launcher uniquement mais aussi sur mon serveur spigot, est ce possible ? 

Merci beaucoup de votre aide et un gros merci pour ce serveur :smile:

**Comment by Litarvan** [comment]
Salut ! Oui c'est possible mais il te faut un développeur pour te mettre en place tout ca. De mon côté je ne prends plus de commandes depuis longtemps donc tu vas devoir trouver quelqu'un, désolé !

Le 13 mai 2019 20:19, DarkScientist <notifications@github.com> a écrit :

Bonjour,
J'ai une question dont je dois vous faire part.

J'ai un site Web MineWeb, un launcher SKCraft et le serveur Yggdrasil.

J'aimerai savoir si je peux réaliser ces actions :
Est il possible d'avoir l'authentification Yggdrasil liée à MineWeb (ça je sais faire je pense) mais tout en gardant la notion de comptes premiums (en gros, relier les utilisateurs à Mojang pour qu'ils soient premium mais validés via MineWeb.
Je ne souhaite pas l'intégrer sur mon launcher uniquement mais aussi sur mon serveur spigot, est ce possible ?

Merci beaucoup de votre aide et un gros merci pour ce serveur 😄

**Comment by DarkScientist** [comment]
Hello,
Oui à quelle question x)?
Celle sur mojang ou celle sur spigot ou les deux ^^ ?
Merci x)

**Comment by Litarvan** [comment]
Les deux, ça va ensemble

Le 14 mai 2019 08:03, DarkScientist <notifications@github.com> a écrit :

Hello,
Oui à quelle question x)?
Celle sur mojang ou celle sur spigot ou les deux ^^ ?
Merci x)

**Comment by DarkScientist** [comment]
Donc le serveur yggdrasil peut s'associer à mojang ! Génial !
Tu aurais un lien vers de la doc ou quelque chose qui traite ça, j'essaierai de voir ce que je peux faire ^^
