### ISSUE TITLE
Cannot declare class Core\Config

### ISSUE THREAD

**Issue by Dabsunter** [TheShark34/OpenAuth-Server#3]
Bonjour,
J'ai correctement installé le serveur OpenAuth sur mon installation [xampp](https://www.apachefriends.org/fr/index.html), mais impossible de le faire fonctionner.
Lorsque que j'effectue une mauvaise requête en utilisant autre chose de POST, j'ai la "bonne erreur" :

``` json
{
    "error":"Method Not Allowed",
    "errorMessage":"The method specified in the request is not allowed for the resource identified by the request URI"
}
```

Mais dans tout les autres cas j’obtiens ceci :

> <b>Fatal error</b>:  Cannot declare class Core\Config, because the name is already in use in <b>C:\xampp\htdocs\keyrisium\core\Config.php</b> on line <b>31</b>

![Exemple concret](https://monosnap.com/file/MLDDxBSMUKjRLcmHi1En8RshQ3ynM6.png)

**Comment by Dabsunter** [comment]
Autant pour moi j'ai finis par trouver la branche 2.0.
Mais dans ce cas il serait cool de merger cette branche sur master ou d'indiquer clairement qu'une version 2 est présente. :wink:

**Comment by Vahelnir** [comment]
Pour l'erreur, c'est effectivement plutot étrange car la V1 est fonctionnelle (Normalement).
Effectivement, il y a une V2 mais j'attendais que Litarvan me dise si je pouvais la rendre "publique".
Tout est fonctionnel avec la V2 ?

**Comment by Dabsunter** [comment]
Pour l'instant aucun problème recensés sur la v2 😉.
Je laisse cette issue ouverte tant que le problème n'est pas confirmé, mais libre à vous de la fermer car mon problème est résolu 😀.

**Comment by Litarvan** [comment]
Je pense oui que c'est résolu, si tu as un problème avec la V2 préviens-nous ! Si tout vas bien, je pense qu'on pourra la publier officiellement après un petit nettoyage et quelques petites finalisations ^^

Bonne continuation à toi !
