### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Sebclem** [TheShark34/OpenAuth-Server#6]
Salut!

Je vient d'installer mon serveur sur une Raspberry, une fois configurer, quand j'essaie de me connecter avec OpenAuth Client, j'ai une AuthenticationException.

- getCause me retourne "Remote"
- getError ->"Internal server error"
- getErrorMessage -> "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">"

Je commence à bien m'y connaitre en Java, par contre en web je n'y connais rien...

Du coup, Help please x)

**Comment by Litarvan** [comment]
T'as bien configuré la BDD ? Vérifie les logs d'erreur apache

**Comment by Sebclem** [comment]
Au niveau des log, quand j'ai j'utilise app/register.php

`[Fri Feb 10 22:18:11.325884 2017] [:error] [pid 6828] [client xx.xxx.xxx.211:1807] PHP Fatal error:  Class 'Core\\Queries' not found in /var/www/html/app/register.php on line 31, referer: http://seb6596.freeboxos.fr/app/register.php`

Par contre, pour AuthenticationException, j'ai pas d'erreur o_O ??? Mais dans acces.log, j'ai ça :
`[10/Feb/2017:22:21:15 +0100] "POST /authenticate HTTP/1.1" 404 517 "-" "Java/1.8.0_111"`

**Comment by Litarvan** [comment]
Mmmh c'est pas normal ça devrait pas faire ça, t'as un dossier vendor ?

**Comment by Sebclem** [comment]
Hum.... Non,
Sur mon serve sa donne sa:

app  
|- authenticate.php        
|- invalidate.php
|- logout.php
|- refresh.php
|-register.php
|- validate.php
core
|- Config.php
|- Database.php
|- functions.php
|- Queries.php
config_base.php  
config.php    
index.php

**Comment by Litarvan** [comment]
Il faut l'extension mod_rewrite sur ton serveur

**Comment by Sebclem** [comment]
Je vient de l'activer, mais toujours la même erreur, je vient de faire un test sur un serveur de liveHost, j'ai la même erreur avec le register

**Comment by Litarvan** [comment]
Tu vas sur quel url ? Il faut aller sur /register, pas /app/register.php

**Comment by Sebclem** [comment]
Si je vais sur /register j'ai un 404, j'ai vu que tu avais un autre version, je pense que je vais faire un test avec celle ci

**Comment by Litarvan** [comment]
C'est que mod_rewrite n'est pas activé, tu as AllowOverride à All dans la config apache (yen a plusieurs) ? T'as redémarré apache aussi ?

**Comment by Sebclem** [comment]
Ah c'est bon ! il me manquait les AllowOverride à All,  tout fonctionne,

Merci beaucoup !
