### ISSUE TITLE
Erreur CHMOD

### ISSUE THREAD

**Issue by Ohw222** [TheShark34/OpenAuth-Server#7]
Bonjour,
Il se trouve que pour mon serveur, je souhaite utiliser votre version serveur de openauth mais il me dit que le chmod n'est pas en 777 alors qu'il l'est... Que faire ?
Cordialement,
Ohw

**Comment by Litarvan** [comment]
Habituellement il n'est pas sensé le signaler directement, pouvez vous faire une capture d'écran ?
