### ISSUE TITLE
Le compte ne s'enregistre pas

### ISSUE THREAD

**Issue by MelaineGerard** [TheShark34/OpenAuth-Server#8]
Bonsoir, quand j'essaye de me créer un compte sur mon serveur Openauth, il me dis que je me suis bien inscrit mais mon compte n'apparait pas dans la base de donnée. 
Pourriez vous m'aider ?
Cordialement
SkitDev

**Comment by Litarvan** [comment]
OpenAuth-Server n'est pas vraiment utilisable sans modification pour l'intégrer à la base de donnée
