### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by Azerosse** [TheShark34/OpenAuth-Server#9]
Bonjour je viens d'installer OpenAuth-server avec la méthode manuelle car impossible d'accéder à la page avec installer.php je ne comprend pas pourquoi ... Bref j'ai effectuer un composer update dans le dossier server tout s'est bien passé je glisse alors tout pour upload une fois l'upload terminé je me rend sur http://monsite/server/ je peux alors rentrer les informations concernant ma base de donnée cependant une fois les informations rentrées une page blanche s'affiche et je ne peux plus rien faire voici l'erreur : 
![Sans titre3](https://user-images.githubusercontent.com/48381054/54071813-43a36f00-4272-11e9-9fd9-675b00594086.png)

**Comment by Vahelnir** [comment]
Bonjour,
J'imagine que tu utilises la 2.0 puisque tu évoques l'utilisation de Composer.
Il nous faudrait plus d'information, actuellement les erreurs PHP sont désactivées et c'est pour cela que tu n'as qu'une erreur 500.
Pour obtenir plus d'informations, tu as deux moyens:
- Aller regarder dans les logs apache/nginx/httpd/autre et de copier/coller les lignes pouvant indiquer ce qu'il se passe.
- Ou rajouter **provisoirement** 
  ```php
  error_reporting(E_ALL);
  ini_set('display_errors', 1);
  ```
  en haut du fichier index.php, dans la balise PHP.

**Comment by Azerosse** [comment]
Bonjour, merci de cette réponse rapide j'ai rajouté provisoirement ces deux lignes dans le fichier index.php et maintenant quand je vais sur http://monsite/server/ j'obtient ce message : 
![Sans titre3](https://user-images.githubusercontent.com/48381054/54083083-77889e00-431f-11e9-91c2-75b0388b2f30.png)

Donc je pense qu'il faut modifier le fichier DatabaseManager.php ? 

Voici la ligne 65 du fichier en question

![Sans titre5](https://user-images.githubusercontent.com/48381054/54083123-f7af0380-431f-11e9-9203-efb1f1b49f95.png)

**Comment by Vahelnir** [comment]
L'erreur se produit car le package qui s'occupe de la base de données requiert PHP 7.1 afin de fonctionner.
Il faut éviter de modifier les fichiers situés dans ./vendor/ puisqu'ils sont réécrits à chaque update (ou presque).

J'imagine que tu as téléchargé les packages avec Composer sur ton PC et que tu as dû utiliser PHP 7.1. Il est normalement censé te télécharger la version 5.2 du package illuminate/database.

Pour régler ce problème, tu peux:
 - download tous les vendors mais en utilisant PHP 5 et non PHP 7.1.
 - ou utiliser PHP 7.1 côté serveur.

**Comment by Azerosse** [comment]
Merci ça fonctionne
